### ISSUE TITLE
重构测试函数

### ISSUE THREAD

**Issue by Irk9737** [JoceHYJ/GinLearning#4]
https://github.com/JoceHYJ/GinLearning/blob/490050223ed5e7d17e0b9bbd9e788c77b7e6eff6/web/router_test.go#L236 需要重构，将 https://github.com/JoceHYJ/GinLearning/blob/490050223ed5e7d17e0b9bbd9e788c77b7e6eff6/web/router_test.go#L287 作为用例传入 `args` 里面，构建好 `fields` 里面的路由树后调用 `findRoute` 方法查询

**Comment by JoceHYJ** [comment]
这样吗？
https://github.com/JoceHYJ/GinLearning/blob/3df5d25d4a637948df97b7572bc4cbeedfe46e5d/web/router_test.go#L411

**Comment by Irk9737** [comment]
> 这样吗？
> 
> https://github.com/JoceHYJ/GinLearning/blob/3df5d25d4a637948df97b7572bc4cbeedfe46e5d/web/router_test.go#L411

r 也可以作为参数在test case中定义好。mockRoute := xxx （这样就可以从奇奇怪怪的路由树里面查找了）

**Comment by Irk9737** [comment]
> > 这样吗？
> > https://github.com/JoceHYJ/GinLearning/blob/3df5d25d4a637948df97b7572bc4cbeedfe46e5d/web/router_test.go#L411
> 
> r 也可以作为参数在test case中定义好。mockRoute := xxx （这样就可以从奇奇怪怪的路由树里面查找了）

比如在https://github.com/JoceHYJ/GinLearning/blob/8336d8d14c175f8d0db9b4595b9fdd0e6b204796/web/router_test.go#L294
中可以放 mockRoute 然后在https://github.com/JoceHYJ/GinLearning/blob/8336d8d14c175f8d0db9b4595b9fdd0e6b204796/web/router_test.go#L365
中通过 
```go
n, found := tt.fields.route.findRoute(tt.args.method, tt.args.path)
```
来查找路由
